apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: makeit404/user
      context: user-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .  
    - image: makeit404/course
      context: course-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: makeit404/purchase
      context: purchase-srv
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .        
    - image: makeit404/makeit-client
      context: makeit-client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.{ts,tsx}"
            dest: .