name: deploy-client

on:
  push:
    branches: 
      - main 
  # pull_request: 
  #   branches: 
  #     - main       
    paths:
      - 'makeit-client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd makeit-client && docker build -t makeit404/makeit-client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push makeit404/makeit-client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save e6dc4d96-e926-4655-a72e-75a8d96eafe8
      - run: kubectl rollout restart deployment client-deployment
